//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingEvent
    {
        public int ParkingEventId { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public int PaymentState { get; set; }
        public int UserId { get; set; }
        public int ParkingId { get; set; }

        [JsonIgnore]
        public virtual Parking Parking { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
