//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        public int ParkingId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> HourRate { get; set; }
    }
}
